In [2]:
import numpy as np
np.random.seed(10)  
a = np.random.rand(2, 3)
b = np.random.randn(3, 2)
c = np.random.rand(6)
d = np.random.randint(1, 100, 6)
c = np.reshape(c, (2, 3))
d= d.reshape(2, -1)

print('a 형태:', a.shape, '\n', a)
print('b 형태:', b.shape, '\n', b)
print('c 형태:', c.shape, '\n', c)
print('d 형태:', d.shape, '\n', d)

print('다차원 객체 1차원 변환 방법')
print('a =', a.flatten())
print('b =', np.ravel(b))
print('c =', np.reshape(c, (-1, )))
print('d =', d.reshape(-1, ))

a 형태: (2, 3) 
 [[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]]
b 형태: (3, 2) 
 [[ 0.62133597 -0.72008556]
 [ 0.26551159  0.10854853]
 [ 0.00429143 -0.17460021]]
c 형태: (2, 3) 
 [[0.81262096 0.61252607 0.72175532]
 [0.29187607 0.91777412 0.71457578]]
d 형태: (2, 3) 
 [[14 26 14]
 [93 87 31]]
다차원 객체 1차원 변환 방법
a = [0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665]
b = [ 0.62133597 -0.72008556  0.26551159  0.10854853  0.00429143 -0.17460021]
c = [0.81262096 0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
d = [14 26 14 93 87 31]


In [ ]:
import cv2

image = cv2.imread("", cv2.IMREAD_COLOR)
if image is None: raise Exception("영상 파일 읽기 오류 발생")

x_axis = cv2.flip(image, 0)
y_axis = cv2.dlip(image, 1)
xy_axis = cv2.dlip(image, -1) # -1 은 x축 y축 flip
rep_image = cv2.repeat(image, 1, 2)
trans_image = cv2.transpose(image)

## 각 행렬을 영상으로 표시
